{!! Html::script('https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js') !!}
{!! Html::script(asset('/js/layoutPartner.js')) !!}
{!! Html::script(asset('/js/laroute.js')) !!}
{{--{!! Html::script(asset('/js/PartnerSite.js')) !!}--}}
{{--{!! Html::script(asset('/js/workingWithMaps.js')) !!}--}}
{!! Html::script('https://cdnjs.cloudflare.com/ajax/libs/metisMenu/1.1.3/metisMenu.min.js') !!}
{!! Html::script('https://cdnjs.cloudflare.com/ajax/libs/jQuery-slimScroll/1.3.0/jquery.slimscroll.min.js') !!}
{!! Html::script('https://cdnjs.cloudflare.com/ajax/libs/jquery.nicescroll/3.6.8-fix/jquery.nicescroll.min.js') !!}
{!! Html::script('https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js') !!}
